Fix build errors when using C++17
/usr/local/include/tango/log4tango/Level.hh:120:6: error: ISO C++1z does not allow dynamic exception specifications
      throw(std::invalid_argument);
      ^~~~~
In file included from /usr/local/include/tango/tango.h:115:0,
                 from src/tango/deviceproxy_pool.hpp:12,
                 from src/tango/deviceproxy_pool.cpp:1:
/usr/local/include/tango/device_2.h:260:9: error: ISO C++1z does not allow dynamic exception specifications
         throw(Tango::DevFailed, CORBA::SystemException);
         ^~~~~
/usr/local/include/tango/device_2.h:285:2: error: ISO C++1z does not allow dynamic exception specifications
  throw(Tango::DevFailed, CORBA::SystemException);
  ^~~~~
/usr/local/include/tango/device_2.h:311:2: error: ISO C++1z does not allow dynamic exception specifications
  throw(Tango::DevFailed, CORBA::SystemException);

Dynamic exception specifications are deprecated since C++11
(see: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0003r0.html)
but it doesn't seems mandatory remove these when using C++17.
Unfortunately GCC treats these as errors so remove these anyway
to make it happy.